### ISSUE TITLE
App crashed upon pressing Sign Up button

### ISSUE THREAD

**Issue by ljensen505** [MuongKimhong/toschat#1]
Installed using the provided script, which seemed to go just fine. The app launched just fine, but when pressing the Sign Up button, I got the following error:

![image](https://github.com/MuongKimhong/toschat/assets/60709632/f7dd1b5c-23a0-446b-be10-a49aa62ffb82)

I'm running pop os, which one would expect to behave the same as Ubuntu, and using wezterm. I did navigate and press the Sign Up button using the keyboard rather than the mouse (not sure if that's relevant though).

**Comment by ljensen505** [comment]
Confirmed that Sign Up works as expected when using the mouse. The crash only happens when using keyboard-exclusive navigation.

**Comment by MuongKimhong** [comment]
Issue #1 is fixed. Thank you for feedback!
